title: Wykopowa liga typerów
description: Zasady wykopowej ligi typerów MotoGP

plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
    - platform: wykop
      user_url: "https://wykop.pl/ludzie/MirkoLigaMotoGP"
      title:  MirkoLigaMotoGP na Wykopie
    - platform: discord
      user_url: "https://discord.com/invite/JnUwtH95Br"
      title: Discord server

header_pages:
  - zasady.md
